Converting Detailed Drug Dataset to a Crosstab of NPI vs Drug Claims

In [2]:
import pandas as pd
import numpy as np

Imports CSV file from the Prescriber Summary Dataset

In [3]:
ps_df = pd.read_csv("data\Prescriber_Info.txt", sep = '\t', low_memory = False)
#another large Dataset

In [30]:
ps_df_new = ps_df[["npi", "specialty_description", "brand_claim_count", "brand_drug_cost", "generic_claim_count", "generic_drug_cost", "nppes_provider_city", "nppes_provider_zip5", "total_claim_count", "total_drug_cost", "nppes_provider_state"]] #taking necessary columns only

Organize a Dataset to determine the top 10 providing States

In [5]:
sort_state_df = ps_df_new.groupby("nppes_provider_state").sum() #group by state
sort_state_df.insert(0, "counts", ps_df_new.groupby("nppes_provider_state").size()) # creates a count column

In [6]:
sort_state_df.sort_values("counts", ascending = False, inplace = True) #sorts based off most providers

In [7]:
sort_state_df.head()

,counts,brand_claim_count,brand_drug_cost,generic_claim_count,generic_drug_cost,nppes_provider_zip5,total_claim_count,total_drug_cost
nppes_provider_state,,,,,,,,
CA,119867,23520307.0,1.026083e+10,108809810.0,3.001003e+09,1.113950e+10,139100291,1.568462e+10
NY,92548,17988335.0,8.257708e+09,74480099.0,2.334745e+09,1.073915e+09,97955185,1.230151e+10
TX,73753,15497894.0,7.025161e+09,74401668.0,2.080232e+09,5.687859e+09,94359394,1.074438e+10
FL,70951,16326687.0,7.400670e+09,86519235.0,2.161895e+09,2.361516e+09,107539136,1.122481e+10
PA,57589,12293523.0,5.181697e+09,60256135.0,1.581843e+09,1.017988e+09,75720850,7.761967e+09

In [8]:
topTen = sort_state_df.index.tolist()[0:10]# pulls out top 10 largest providing states

REQUIRES the Detailed Drug Dataset and Provider Summary Dataset to be downloaded from https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Medicare-Provider-Charge-Data/PartD2017.html

In [9]:
dd_df = pd.read_csv("data\Detailed_Drugs.txt", sep = '\t', header = 0, low_memory = False)

In [41]:
for state in topTen: #sections off dd_df of ata of all thetop ten states
    temp_df = dd_df[dd_df['nppes_provider_state'].map(lambda x: str(x) == state)]
    temp_df.to_csv("data\state\dd_df\dd_df_" + state + ".csv", index = False)
    print(state)

CA
NY
TX
FL
PA
IL
OH
MI
MA
NC

In [31]:
for state in topTen: #sections off ps_df of all thetop ten states
    temp_df = ps_df_new[ps_df_new['nppes_provider_state'].map(lambda x: str(x) == state)]
    temp_df.to_csv("data\state\ps_df\ps_df_" + state + ".csv", index = False)
    print(state)

CA
NY
TX
FL
PA
IL
OH
MI
MA
NC

In [13]:
from os import listdir

In [32]:
ps_csv_list = listdir("data\state\ps_df")
dd_csv_list = listdir("data\state\dd_df")
print(ps_csv_list)
print(dd_csv_list)

['ps_df_CA.csv', 'ps_df_FL.csv', 'ps_df_IL.csv', 'ps_df_MA.csv', 'ps_df_MI.csv', 'ps_df_NC.csv', 'ps_df_NY.csv', 'ps_df_OH.csv', 'ps_df_PA.csv', 'ps_df_TX.csv']
['dd_df_CA.csv', 'dd_df_FL.csv', 'dd_df_IL.csv', 'dd_df_MA.csv', 'dd_df_MI.csv', 'dd_df_NC.csv', 'dd_df_NY.csv', 'dd_df_OH.csv', 'dd_df_PA.csv', 'dd_df_TX.csv']

In [62]:
dd_df = pd.read_csv('data\state\dd_df\\' + dd_csv_list[0])

In [68]:
dd_df.head()

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_city,nppes_provider_state,specialty_description,description_flag,drug_name,generic_name,bene_count,...,total_30_day_fill_count,total_day_supply,total_drug_cost,bene_count_ge65,bene_count_ge65_suppress_flag,total_claim_count_ge65,ge65_suppress_flag,total_30_day_fill_count_ge65,total_day_supply_ge65,total_drug_cost_ge65
0,1003000837,JOHN,RICHARD,SANTA MARIA,CA,Nurse Practitioner,S,MIRTAZAPINE,MIRTAZAPINE,NaN,...,18.0,540,333.17,NaN,*,NaN,*,NaN,NaN,NaN
1,1003001017,NICHOLS,LAWRENCE,LA PALMA,CA,Dermatology,S,BETAMETHASONE VALERATE,BETAMETHASONE VALERATE,98.0,...,251.5,5883,10797.59,86.0,NaN,204.0,NaN,211.0,4965.0,9049.98
2,1003001017,NICHOLS,LAWRENCE,LA PALMA,CA,Dermatology,S,CLINDAMYCIN PHOSPHATE,CLINDAMYCIN PHOSPHATE,NaN,...,11.0,142,622.96,NaN,*,NaN,*,NaN,NaN,NaN
3,1003001017,NICHOLS,LAWRENCE,LA PALMA,CA,Dermatology,S,CLOBETASOL PROPIONATE,CLOBETASOL PROPIONATE,11.0,...,17.0,375,4248.23,11.0,NaN,17.0,NaN,17.0,375.0,4248.23
4,1003001017,NICHOLS,LAWRENCE,LA PALMA,CA,Dermatology,S,DOXYCYCLINE HYCLATE,DOXYCYCLINE HYCLATE,NaN,...,20.0,535,2648.69,NaN,*,20.0,NaN,20.0,535.0,2648.69

In [65]:
npi_drug_cross_df = pd.crosstab(dd_df["npi"], dd_df["drug_name"] , values=dd_df["total_claim_count"], 
                                  aggfunc=np.sum)

In [69]:
npi_drug_cross_df = npi_drug_cross_df.fillna(0) #Replaces NaN w/ 0

In [70]:
npi_drug_cross_df.head()

drug_name,1ST TIER UNIFINE PENTIPS PLUS,ABACAVIR,ABACAVIR-LAMIVUDINE,ABACAVIR-LAMIVUDINE-ZIDOVUDINE,ABELCET,ABILIFY,ABILIFY MAINTENA,ABRAXANE,ABSTRAL,ACAMPROSATE CALCIUM,...,ZYFLO CR,ZYKADIA,ZYLET,ZYLOPRIM,ZYMAXID,ZYPREXA,ZYPREXA RELPREVV,ZYPREXA ZYDIS,ZYTIGA,ZYVOX
npi,,,,,,,,,,,,,,,,,,,,,
1003000837,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003001017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003001132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003001363,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003001645,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
ps_df = pd.read_csv('data\state\ps_df\\' + ps_csv_list[0])

In [72]:
ps_df.head()

,npi,specialty_description,brand_claim_count,brand_drug_cost,generic_claim_count,generic_drug_cost,nppes_provider_city,nppes_provider_zip5,total_claim_count,total_drug_cost,nppes_provider_state
0,1003000175,Dentist,0.0,0.00,18.0,113.81,LA PUENTE,91744.0,18,113.81,CA
1,1003000639,Cardiac Surgery,NaN,NaN,NaN,NaN,LOS ANGELES,90095.0,25,1336.07,CA
2,1003000837,Nurse Practitioner,15.0,19969.83,87.0,2154.60,SANTA MARIA,93454.0,102,22124.43,CA
3,1003001017,Dermatology,115.0,9090.95,448.0,22250.89,LA PALMA,90623.0,563,31341.84,CA
4,1003001132,Family Practice,17.0,956.30,99.0,1649.05,SAN LUIS OBISPO,93409.0,116,2605.35,CA

In [73]:
ps_df = ps_df.sort_values(by=["npi","specialty_description"]) #sort
ps_df = ps_df.set_index("npi")

In [75]:
ps_df = ps_df.fillna(0)

In [77]:
ps_dd_df = pd.concat([npi_drug_cross_df,ps_df], axis=1, join='inner')#concatnate states togethor

In [78]:
ps_dd_df.head()

,1ST TIER UNIFINE PENTIPS PLUS,ABACAVIR,ABACAVIR-LAMIVUDINE,ABACAVIR-LAMIVUDINE-ZIDOVUDINE,ABELCET,ABILIFY,ABILIFY MAINTENA,ABRAXANE,ABSTRAL,ACAMPROSATE CALCIUM,...,specialty_description,brand_claim_count,brand_drug_cost,generic_claim_count,generic_drug_cost,nppes_provider_city,nppes_provider_zip5,total_claim_count,total_drug_cost,nppes_provider_state
npi,,,,,,,,,,,,,,,,,,,,,
1003000837,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Nurse Practitioner,15.0,19969.83,87.0,2154.60,SANTA MARIA,93454.0,102,22124.43,CA
1003001017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Dermatology,115.0,9090.95,448.0,22250.89,LA PALMA,90623.0,563,31341.84,CA
1003001132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Family Practice,17.0,956.30,99.0,1649.05,SAN LUIS OBISPO,93409.0,116,2605.35,CA
1003001363,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Anesthesiology,264.0,118168.36,1985.0,87998.83,EL CENTRO,92243.0,2249,206167.19,CA
1003001645,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Infectious Disease,257.0,389050.92,398.0,52089.59,SACRAMENTO,95815.0,655,441140.51,CA

In [79]:
for csv in range(len(topTen)):
    dd_df = pd.read_csv('data\state\dd_df\\' + dd_csv_list[csv]) #reads dd_df state csv files
    npi_drug_cross_df = pd.crosstab(dd_df["npi"], dd_df["drug_name"] , values=dd_df["total_claim_count"], 
                                  aggfunc=np.sum) #uses drug_name which is the brand names
    npi_drug_cross_df = npi_drug_cross_df.fillna(0) #Replaces NaN w/ 0
    ps_df = pd.read_csv('data\state\ps_df\\' + ps_csv_list[csv]) #reads ps_df state csv files
    ps_df = ps_df.sort_values(by=["npi","specialty_description"]) #sort
    ps_df = ps_df.set_index("npi")
    ps_df = ps_df.fillna(0) #if the column doesn't normally take integer/float input, it was still replaced by 0.0
    #doesn't really matter because those columns will be dropped
    ps_dd_df = pd.concat([npi_drug_cross_df,ps_df], axis=1, join='inner')#concatnate states togethor
    

   
    
    #secondary dataset
    specialty_df = ps_dd_df.groupby("specialty_description").sum()
    specialty_df.insert(0, "counts", ps_dd_df.groupby("specialty_description").size()) # creates a count column
    specialty_df.insert(1, "generic_brand_ratio_cost", specialty_df["brand_drug_cost"]/specialty_df["generic_drug_cost"], True)
    specialty_df.reset_index("specialty_description", inplace=True)
    specialty_df.sort_values("generic_brand_ratio_cost", inplace = True, na_position = "first")
    
    #insert generic brand ratio costs
    ps_dd_df.insert(0, "generic_brand_ratio_cost", ps_dd_df["brand_drug_cost"]/ps_dd_df["generic_drug_cost"], True)
    #Remove any inf, or NaN, or 0 values from Generic Brand Ratio Costs because those lack
    #predictive value and creates a Log transformed value for Generic and Brand Drug costs -
    #We are looking at people with significant amounts of both Generic and Brand name Drugs 
    #prescribed
    
    ps_dd_df.replace(np.inf, np.nan, inplace = True) #remove inf
    ps_dd_df.dropna( inplace = True)
    ps_dd_df.drop(ps_dd_df[ps_dd_df["generic_brand_ratio_cost"]==0].index , inplace = True)
    # remove NaN and 0 and inf
    
    ps_dd_df["log_brand_cost"] = ps_dd_df["brand_drug_cost"].apply(lambda x : np.log10(x)) #creates a log of the cost data
    ps_dd_df["log_generic_cost"] = ps_dd_df["generic_drug_cost"].apply(lambda x : np.log10(x))
    
    
    specialty_df.replace(np.inf, np.nan, inplace = True)
    specialty_df.dropna(inplace =True)
    specialty_df.drop(specialty_df[specialty_df["generic_brand_ratio_cost"]==0].index , inplace = True)
    #remove NaN and 0 and inf
    
    specialty_df["log_brand_cost"] = specialty_df["brand_drug_cost"].apply(lambda x : np.log10(x)) #creates a log of the cost data
    specialty_df["log_generic_cost"] = specialty_df["generic_drug_cost"].apply(lambda x : np.log10(x))
    specialty_df["Index"] = range(len(specialty_df))
    specialty_df = specialty_df.set_index(specialty_df["Index"]) # resets index w/o moving rows
     
        
    #saves to csv    
    ps_dd_df.to_csv("data\state\combined_df\combined_df_" + topTen[csv] + '.csv', index=False)
    specialty_df.to_csv("data\state\combined_df\specialty_df\specialty_df_" + topTen[csv] + '.csv',index=False)
    print(topTen[csv])

CA
NY
TX
FL
PA
IL
OH
MI
MA
NC

In [81]:
test = pd.read_csv("data\state\combined_df\specialty_df\specialty_df_CA.csv")

In [82]:
test.head()

,Index,specialty_description,counts,generic_brand_ratio_cost,1ST TIER UNIFINE PENTIPS PLUS,ABACAVIR,ABACAVIR-LAMIVUDINE,ABACAVIR-LAMIVUDINE-ZIDOVUDINE,ABELCET,ABILIFY,...,brand_claim_count,brand_drug_cost,generic_claim_count,generic_drug_cost,nppes_provider_zip5,total_claim_count,total_drug_cost,log_brand_cost,log_generic_cost,Index.1
0,0,Licensed Vocational Nurse,1,0.043265,0.0,0.0,0.0,0.0,0.0,0.0,...,14.0,117.98,133.0,2726.93,9.592800e+04,147,2844.91,2.071808,3.435674,0
1,1,Peripheral Vascular Disease,5,0.222528,0.0,0.0,0.0,0.0,0.0,0.0,...,35.0,13383.21,2510.0,60141.74,4.686210e+05,3382,307826.14,4.126560,4.779176,1
2,2,Dentist,11700,0.263340,0.0,0.0,0.0,0.0,0.0,0.0,...,4011.0,920238.22,444453.0,3494488.98,1.086932e+09,844640,9176643.03,5.963900,6.543384,2
3,3,Clinical Pharmacology,2,0.313610,0.0,0.0,0.0,0.0,0.0,0.0,...,101.0,22550.48,1446.0,71906.21,1.872060e+05,1677,144581.94,4.353156,4.856766,3
4,4,Physical Therapist in Private Practice,7,0.436339,0.0,0.0,0.0,0.0,0.0,0.0,...,51.0,5293.90,838.0,12132.53,6.422900e+05,1098,83590.49,3.723776,4.083951,4